
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Common' do
project 'Common.xcodeproj'

pod 'Nimbus/Core'
pod 'Nimbus/AttributedLabel'
pod 'Nimbus/Badge'
pod 'Nimbus/Models'
pod 'Nimbus/WebController'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'Masonry'

end
